name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11","3.12","3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --group test
        uv pip install -e .

    - name: Run tests with snapshots
      id: run_tests
      run: |
        uv run pytest tests/ -v

    - name: Upload snapshot comparison on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: snapshot-diffs-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          **/snapshots
          **/__snapshot__
